name: Build Paddle

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: paddle
        shell : bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pyinstaller pygame

      - name: Build executable
        run: |
          pyinstaller \
            --onefile \
            --hidden-import=scenes.welcome_screen \
            --hidden-import=scenes.scene_1 \
            --hidden-import=scenes.options_screen \
            main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: paddle-${{ matrix.os }}
          path: |
            paddle/dist/**
